package exporter

import (
	"bytes"
	"github.com/Dreamacro/clash/log"
	"github.com/fogleman/gg"
	"github.com/thank243/StairUnlocker-Bot/config"
	"image/png"
	"sort"
	"strconv"
	"strings"
	"time"
)

const W = 1000

func getXFix(i int) float64 {
	f := 2.3
	return W/f + (W-40-(W-40)/f)/4*float64(i)
}

func Export(streamMediaUnlockMap map[string][]uint16) (*bytes.Buffer, error) {
	streamMediaNames := []string{"Netflix", "HBO", "DisneyPlus", "Youtube Premium"}
	H := len(streamMediaUnlockMap)*25 + 100
	dc := gg.NewContext(W, H)
	dc.SetRGB(1, 1, 1)
	dc.Clear()
	dc.SetRGB(0, 0, 0)
	dc.SetLineWidth(1)
	// load font.
	path := strings.Split(config.ConfigPath, "/")
	path[len(path)-1] = "msyh.ttc"
	err := dc.LoadFontFace(strings.Join(path, "/"), 15)
	if err != nil {
		log.Errorln(err.Error())
		return nil, err
	}

	title := "StairUnlocker Bot"
	dc.DrawString(title, float64((W-len(title)*6)/2), 18)
	dc.SetLineWidth(0.4)
	// draw horizon lines
	for i := 0; i < len(streamMediaUnlockMap)+2; i++ {
		dc.DrawLine(20, 25+float64(i)*25, W-20, 25+float64(i)*25)
		if i == 0 {
			continue
		}
		dc.Stroke()
	}
	// draw vertical lines
	for i := 0; i < 2; i++ {
		dc.DrawLine(20+(W-40)*float64(i), 25, 20+(W-40)*float64(i), float64(H-50))
		dc.Stroke()
	}
	for i := 0; i < len(streamMediaNames); i++ {
		dc.DrawLine(getXFix(i), 25, getXFix(i), float64(H-50))
		dc.Stroke()
	}
	// header
	dc.DrawString("Node Name", getXFix(0)-250, 42.5)
	for i := range streamMediaNames {
		dc.DrawString(streamMediaNames[i], 5+getXFix(i), 42.5)
	}
	// context
	// sort nodes name
	var nameSort []string
	for i := range streamMediaUnlockMap {
		nameSort = append(nameSort, i)
	}
	sort.Strings(nameSort)

	n := 0
	for i := range nameSort {
		dc.DrawString(nameSort[i], 22, 67.5+float64(n)*25)
		for idx := range streamMediaUnlockMap[nameSort[i]] {
			if streamMediaUnlockMap[nameSort[i]][idx] != 0 {
				dc.DrawString(strconv.Itoa(int(streamMediaUnlockMap[nameSort[i]][idx]))+"ms", 5+getXFix(idx), 67.5+float64(n)*25)
			} else {
				dc.SetRGB(1, 0, 0)
				dc.DrawString("None", (getXFix(1)-getXFix(0))/2-16+getXFix(idx), 67.5+float64(n)*25)
				dc.SetRGB(0, 0, 0)
			}
		}
		n++
	}
	// bottom
	dc.DrawString("Generated by @stairunlock_test_bot (https://github.com/thank243/StairUnlocker-Bot)", 20, float64(H)-30)
	dc.DrawString(time.Now().Round(1*time.Millisecond).String(), W-280, float64(H)-10)
	buf := new(bytes.Buffer)
	err = png.Encode(buf, dc.Image())
	return buf, err
}
